version: '3.8'
services:
  rabbitmq-server:
    image: rabbitmq:3.8.5-management
    hostname: "rabbitmq-server"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  database:
    image: fernandopfh/database:1.0.0
    hostname: "mysql-server"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest
      BASE_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    volumes:
      - "./Database/Data:/var/lib/mysql"

  imagedatabase:
    image: fernandopfh/imagedatabase:1.0.0
    volumes:
      - "./ImagesDB/public/images:/public/images"
    tty: true
    ports:
      - "5100:5000"

  db-management:
    image: adminer:4.7.7-standalone
    ports:
      - 8080:8080

  apigateway:
    image: fernandopfh/apigateway:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
    tty: true
    ports:
      - "5050:5000"

  login-get:
    image: fernandopfh/login-get:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    tty: true

  account-data-get:
    image: fernandopfh/account-data-get:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    tty: true

  account-data-set:
    image: fernandopfh/account-data-set:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    tty: true

  login-set:
    image: fernandopfh/login-set:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    tty: true

  getprojectssideinfos:
    image: fernandopfh/getprojectssideinfos:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    tty: true

  getuserssideinfos:
    image: fernandopfh/getuserssideinfos:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    tty: true

  searchforprojects:
    image: fernandopfh/searchforprojects:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    tty: true

  project-get:
    image: fernandopfh/project-get:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    tty: true

  project-set:
    image: fernandopfh/project-set:1.0.0
    environment:
      RABBITMQ_HOST_NAME: ${RABBITMQ_HOST_NAME}
      MYSQL_HOST_NAME: ${MYSQL_HOST_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
    tty: true